### ISSUE TITLE
오타: 라인 친구 -> 카카오톡 친구

### ISSUE THREAD

**Issue by spilist** [hunkim/kakao-gpt#3]
리드미 오타를 발견하여 제보합니다.

**Comment by hunkim** [comment]
넵넵. 감사합니다. 아쉽게도 5초 타임아웃으로 제가 context 저장과 읽어오기를 다 삭제해서 지금 봇이 기억상실증에 걸렸을 것입니다.

**Comment by Hiyul1** [comment]
과거에 살고 있는 애슼업을 구해주세요...ㅠ
