### ISSUE TITLE
저 공공기관 근무하는 사람인데 혹시 노하우 전수 정도만 받을 수 있을까요

### ISSUE THREAD

**Issue by florahj** [hunkim/kakao-gpt#6]
다름이 아니라 저는 전북 군산에서 산업안전보건법을 다루는 현직 근로감독관입니다.
저희 관내에서 위험상황신고센터를 운영하려고 합니다.
 - 예를 들어, 건설현장에서 노가다일을 하는 데 떨어질 것 같은 곳에서 안전대나 안전모 등을 안주고 일을 하라고 한다던가 하는 것들을 신고를 받아서, 담당 구역 감독관이 출동해서 현장확인하고 위험상황에 대해 시정지시를 내려 신속하게 위험을 제거하는 일입니다.

문제는 저희는 소방과는 달리 대기인력이 없다시피하다보니, 이를 처리할 인력이 다른 일을 하다가 신고의 처리가 늦어지는 경우가 많은데요,  챗GTP를 써보고 이런 걸 잘 활용해서 쓰면 좋겠다 생각했습니다.

여기 요청을 드리는 이유는 혹시 
1. Chat GPT가 카카오톡 채널로 받은 내용을 저희 측 인풋으로 끌어오는 일,
2. Chat GPT에서 처리를 해서 해당 지역 담당 감독관에게 아웃풋으로 뽑는 일

이 2가지 부분을 어떻게 하는지 잘 몰라서 
그 부분만 간단하게 일러 주시거나하면 
저희가 찾아보고 이 문제를 풀 수 있을 것 같습니다(2는 좀 힘들수도 있긴한데요...)
일단 단순하기만 해도 돌아가기만 하면 아웃소싱할 필요도 본부에서 느낄 겁니다
제가 만든 건 아주 간단한 보안 같은 형편없는 문제들을 내포하고 있을테니까요

끝으로, 저희는 사고가 10건이 나면 그 모든 사람을 살릴 수는 없으나, 한두명의 사람은 저희가 살리고 다닌다고 생각합니다.
그리고 그 일을 올바른 일이라고 믿고 일선에서 일하고 있습니다.
도움을 꼭 부탁드립니다.
카카오톡 채널 "군산부안고창위험상황신고센터"라는 ID를 검색하시면 산안테스트654321이 있습니다.
메일 주소는 suller091@korea.kr입니다.
긴 글 읽어주셔서 감사합니다.

**Comment by hhajime** [comment]
안녕하세요 먼저 일선에서 노력해주심에 감사의 말씀 드립니다.

1,2 번에 해당하는 내용의 프로세스를 더 상세히 알려주시거나,
가정 상황을 예시로 들어주시면, 더 도움줄 수 있는 분들이 많지 않을까 생각해 코멘트 남깁니다.

감사합니다.

**Comment by hunkim** [comment]
저도 1, 2에 대해 자세히 알면 도와드릴수 있을지 고민해 볼수 있을것 같습니다. hunkim@gmail.com으로 자세히 알려주시면 고민해 보겠습니다. 감사합니다.
