### ISSUE TITLE
월100건 이후에는 어떻게 되는 건가요?

### ISSUE THREAD

**Issue by leesh06** [hunkim/kakao-gpt#7]
백건이 리필되는 시점은 1일기준인지 궁금하고,
백건 이상 넘어갔을 때는 비용을 지불하는 건지 사용이 불가능한 건지 어떻게 되는건지 궁금합니다.
비용을 지불한다면 비용 구조나 가격도 궁금하고요.
감사합니다.

**Comment by hunkim** [comment]
일일 100건으로 일단 수정해 두었습니다. 더욱 많은 사람들이 지속가능한 서비스가 되기 위해 어떻게하면 좋을지 고민하고 있습니다.

혹시 불편한 부분이나 어떤 방식으로 하면 좋을지 아이디어 있으시면 알려주세요.
