### ISSUE TITLE
다양하게 공부를 해보고싶은데 오픈 소스는 어려울까요??

### ISSUE THREAD

**Issue by kkobikim** [hunkim/kakao-gpt#8]
다양하게 공부를 해보고싶은데 오픈 소스는 어려울까요??

**Comment by hunkim** [comment]
아무래도 대화를 다루다 보니 오픈소스는 어려울것 같습니다. 많은 분들을 서빙하려고 하다 보니 시스템도 상당히 복잡합니다.
